# site
site_name: Luke's Notes
site_url: https://icecoobe.github.io/notes
site_author: icecoobe
site_description: Pieces of life

# repo
repo_url: https://github.com/icecoobe/notes
edit_uri: edit/main/docs/

# Copyright
# copyright: Copyright &copy; 2025 icecoobe<br>The website content is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>
copyright: Copyright &copy; 2025 icecoobe <a href="https://squidfunk.github.io/mkdocs-material/reference/">Awesome - Material for MkDocs</a>

# Configuration
# ref: https://github.com/krahets/hello-algo/blob/main/mkdocs.yml
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    # - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate 
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/avatar/favicon.png
  
# Plugins
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      auto_caption: false
      caption_position: bottom
  - drawio:
      # Control if hovering on a diagram shows a toolbar for zooming or not
      toolbar: true

      # Control if tooltips will be shown (data-tooltips)
      tooltips: true

      # Increase or decrease the padding around your diagrams
      # (data-border)
      border: 5

      # Control if edit button will be shown in the lightbox view
      # (data-edit)
      edit: true

      # Control if darkmode is supported
      # When activated the color scheme for your diagrams is automatically toggled
      # based on the selected theme. Supports classic mkdocs and mkdocs-material.
      darkmode: true 

extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
  - https://viewer.diagrams.net/js/viewer-static.min.js
  - assets/javascripts/drawio-reload.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.critic
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
extra:
  # remove Made with Material for MkDocs notice
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/icecoobe
      name: icecoobe on GitHub
nav:
  - Home: index.md
  - Linux: 
    - Tools: Linux/awesome-tools.md
    - Shell Script: Linux/best-practices-of-shell-scripts.md
    - FAQ: Linux/FAQ.md
    - Link File: Linux/link.md
  - C/C++: 
    - Encoding: c-cpp/data_encoding.md
    - C: 
      - Overview: c-cpp/c/00.overview.md
      - Tour of C: c-cpp/c/01.tour_of_c.md
    - C++: 
      - Overview: c-cpp/00.overview.md
      - Tour of C++: c-cpp/01.tour_of_cpp.md
      - iterator: c-cpp/iterator.md
      - Basics:
        - virtual: c-cpp/basics/virtual.md
        - final: c-cpp/basics/final.md
        - Pointer and Reference: c-cpp/basics/pointer_and_ref.md
        - RTTI: c-cpp/basics/rtti.md
      - Advanced:
        - Handle C-style Callback: c-cpp/advanced/handle_c_style_callback.md
    - Design Pattern:
      - Template Method: c-cpp/design_pattern/template_method.md
      - Singleton: c-cpp/design_pattern/singleton.md
    - Build: c-cpp/build.md
    - Cross Compilation: c-cpp/cross-compile.md
    - GoogleTest: c-cpp/googletest.md
  - Algorithm: 
    - Overview: algo/overview.md
  - Qt:
    - Overview: Qt/00.overview.md
    - Add UI for class: Qt/add_ui.md
    - Custom Widget: Qt/custom_control.md
    - Plugin: Qt/qt_plugin.md
    - FAQ: Qt/FAQ.md
  - Misc: 
    - Talk: misc/talk.md
    - Thinking: misc/thinking.md
    - Museum: misc/museum.md
    - Collection: misc/collection.md
    - 数字化转型: misc/digital_transformation.md
    - ppt: misc/ppt.md
    
